name: Java CI con Maven

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v4

      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Dar permisos de ejecucion al wrapper
        run: chmod +x mvnw

      - name: Compilar proyecto (Omitiendo tests de BD)
        run: ./mvnw clean package -DskipTests

      - name: Ejecutar pruebas unitarias
        run: ./mvnw test -Dtest=CreateTicketUseCaseTest,GetTicketUseCaseTest

      - name: Subir artefacto
        uses: actions/upload-artifact@v4
        with:
          name: tickets-app
          path: target/*.jar